import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className="text-3xl font-bold underline">Hello world!</h1>
        <div className="relative w-96 m-3 cursor-pointer border-2 shadow-lg rounded-xl items-center">
          {/* Image */}
          <div className="flex h-28 bg-blue-700 rounded-xl items-center justify-center">
            <h1 className="absolute mx-auto text-center right text-2xl text-white">
              Image goes here
            </h1>
          </div>

          {/* Description */}
          <div className="p-2 border-b-2">
            <h6>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis
              beatae nulla, atque et sunt ad voluptatum quidem impedit numquam
              quia? Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Facilis beatae nulla, atque et sunt ad voluptatum quidem impedit
              numquam quia?
            </h6>
          </div>

          {/* Tech stack used */}
          <div className="flex flex-wrap items-center m-2">
            <span className=" border border-blue-300 rounded-2xl px-2 my-1 mx-1">
              #React
            </span>
            <span className=" border border-blue-300 rounded-2xl px-2 my-1 mx-1">
              #Redux
            </span>
            <span className=" border border-blue-300 rounded-2xl px-2 my-1 mx-1">
              #Javascript
            </span>
          </div>

          {/* Links */}
          <div className="flex flex-wrap items-center rounded-b-xl border-t-2 bg-white">
            <button className="border rounded-2xl bg-blue-600 text-white shadow-sm p-1 px-2 m-2">
              Go to Project
            </button>
            <button className="border-2 border-blue-600 rounded-2xl text-blue-600 shadow-sm p-1 px-2 m-2">
              Github
            </button>
          </div>
        </div>
      </main>
    </>
  );
}
